# Generated by Django 4.1.5 on 2023-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('receiver_mail', models.EmailField(blank=True, default=None, max_length=254)),
            ],
        ),
    ]
